development:
  bin_path: "/usr/local/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer

test:
  bin_path: "/usr/local/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer

#production:
    # pid_file: /path/to/app/shared/tmp/searchd.pid
    # searchd_file_path: /path/to/app/shared/db/sphinx
    #pid_file:  /vol/www/apps/ror_tutorial/current/tmp/searchd.pid            #doesn't work
    #searchd_file_path: /vol/www/apps/ror_tutorial/current/tmp/db/sphinx      #doesn't work